discord:
  token: ""
  activity: "YOUR_ACTIVITY"
  boostmodule:
    active: true
    # The command to execute when boosting the server
    command: "YOUR_COMMAND"
  minecraftchat:
    active: true
    # Send a message on discord when a player send a message in the minecraft chat
    channelID: "YOUR_CHANNEL"
  discordchat:
    # Send a message in the minecraft chat when a player send a message in the discord chat
    active: true

