discord:
  token: ""
  activity: "YOUR_ACTIVITY"
  guildid: ""
  boostmodule:
    active: true
    # The command to execute when boosting the server
    command: "YOUR_COMMAND"
    # Your server ID
    serverid: ""
  minecraftchat:
    active: true
    # Send a message on discord when a player send a message in the minecraft chat
    channelID: ""
  discordchat:
    # Send a message in the minecraft chat when a player send a message in the discord chat
    active: true
    channelID: ""
  commands:
    # send a message on a specific channel when you execute a command on minecraft
    # exemple : /dbplus annonce "%player% vien de miner de voter pour le serveur !"
    # annonce:
      # channelID: ""
      # message: "%player% vien de miner de voter pour le serveur !"

